In [12]:
import pandas as pd

/home/shawn/.virtualenvs/TEC/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [13]:
df = pd.read_csv('results/data.csv')

In [14]:
df

,Tick,Second,Min,Hour,Day,Month,Year,Num_mkts,onemkt_rev/mo,onemkt_rev/yr,...,OCEAN_minted_USD/mo,OCEAN_burned_USD/mo,OCEAN_price,RND/mo,rnd_to_sales_ratio,mkts_annual_growth_rate,dao_USD/mo,dao_OCEAN/mo,dao_OCEAN_in_USD/mo,dao_total_in_USD/mo
0,0,0.0,0,0,0,0.000000,0.000000,1.00000,0.0000,0.0000,...,0.00,0.000000,0.007237,0.000,0.00,-0.118,0.000000,0.0,0.000,0.000
1,24,86400.0,1440,24,1,0.033333,0.002740,1.00052,66.6835,66.6835,...,0.00,0.006670,0.007239,626.855,4699.04,0.225,0.121447,27777.8,201.081,201.203
2,48,172800.0,2880,48,2,0.066667,0.005479,1.00108,133.4040,133.4040,...,0.00,0.013347,0.007241,626.981,2348.69,0.225,0.248313,27777.8,201.137,201.385
3,72,259200.0,4320,72,3,0.100000,0.008219,1.00163,200.1620,200.1620,...,0.00,0.020032,0.007243,627.108,1565.24,0.225,0.375320,27777.8,201.192,201.567
4,96,345600.0,5760,96,4,0.133333,0.010959,1.00219,266.9570,266.9570,...,0.00,0.026725,0.007245,627.236,1173.51,0.225,0.502468,27777.8,201.247,201.750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,8664,31190400.0,519840,8664,361,12.033300,0.989041,1.22223,2424.2200,26651.3000,...,7778.71,0.293849,0.007925,8178.940,1391.69,0.225,5.582870,975919.0,7734.340,7739.930
362,8688,31276800.0,521280,8688,362,12.066700,0.991781,1.22291,2425.5700,26732.8000,...,7778.69,0.294176,0.007927,8177.110,1389.83,0.225,5.589080,975469.0,7732.550,7738.140
363,8712,31363200.0,522720,8712,363,12.100000,0.994521,1.22359,2426.9200,26814.4000,...,7778.68,0.294503,0.007929,8175.280,1387.98,0.225,5.595300,975019.0,7730.770,7736.360
364,8736,31449600.0,524160,8736,364,12.133300,0.997260,1.22427,2428.2700,26896.0000,...,7778.66,0.294831,0.007931,8173.450,1386.13,0.225,5.601530,974570.0,7728.980,7734.580
365,8760,31536000.0,525600,8760,365,12.166700,1.000000,1.22495,2429.6200,26977.6000,...,7778.64,0.295159,0.007932,8171.620,1384.28,0.225,5.607760,974120.0,7727.190,7732.800

In [17]:
df.columns

/home/shawn/.virtualenvs/TEC/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Index(['Tick', ' Second', ' Min', ' Hour', ' Day', ' Month', ' Year',
       ' Num_mkts', ' onemkt_rev/mo', ' onemkt_rev/yr', ' allmkts_rev/mo',
       ' allmkts_rev/yr', ' ocean_rev/mo', ' ocean_rev/yr',
       ' ocean_rev_growth/mo', ' ocean_rev_growth/yr', ' ps30_valuation',
       ' overall_valuation', ' fundamentals_valuation',
       ' speculation_valuation', ' tot_OCEAN_supply', ' tot_OCEAN_minted',
       ' tot_OCEAN_burned', ' OCEAN_minted/mo', ' OCEAN_burned/mo',
       ' OCEAN_minted_USD/mo', ' OCEAN_burned_USD/mo', ' OCEAN_price',
       ' RND/mo', ' rnd_to_sales_ratio', ' mkts_annual_growth_rate',
       ' dao_USD/mo', ' dao_OCEAN/mo', ' dao_OCEAN_in_USD/mo',
       ' dao_total_in_USD/mo'],
      dtype='object')

In [18]:
df[' speculation_valuation']

0      5000000.0
1      5001370.0
2      5002740.0
3      5004110.0
4      5005480.0
         ...
361    5519800.0
362    5521310.0
363    5522820.0
364    5524340.0
365    5525850.0
Name:  speculation_valuation, Length: 366, dtype: float64